### ISSUE TITLE
[Bug]: mushroom cards dont work in popup-card

### ISSUE THREAD

**Issue by fxxer** [piitaya/lovelace-mushroom#1218]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I don't now the exact version when it stopped working. I am using custom:popup-card (browser_mod integration https://github.com/thomasloven/hass-browser_mod ) where using custom:auto-entities I am generating list of lights that are on. Clicking on light tu turn on / off stopped working (also mushroom entity card in other popups-cards). Other buttons or entities not using mushroom cards are working properly.

### Expected Behavior

Clicking on mushroom entity should do default action / toggle entity state also in custom:popup-card

### Steps To Reproduce

1. My versions:
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

Mushroom v3.0.5
browser_mod 2.3.0

2. try the card I coppied in "Context"
3. I can't use mushroom buttons in popups

### Context

Here's the card for example
```yaml
type: custom:popup-card
entity: switch.template_lights
title: All Lights
dismissable: true
card:
  cards:
    - type: custom:mushroom-light-card
      entity: switch.template_lights
    - type: custom:auto-entities
      filter:
        exclude:
          - domain: automation
          - entity_id: group.all_lights
          - entity_id: '*_1*'
          - entity_id: '*_2*'
          - entity_id: '*_3*'
          - entity_id: '*_4*'
          - entity_id: '*_5*'
          - entity_id: light.presence_simulation
        include:
          - domain: light
            attributes:
              supported_features: '>= 44'
            options:
              type: custom:mushroom-light-card
              show_brightness_control: true
              use_light_color: true
              show_color_temp_control: true
              show_color_control: true
              collapsible_controls: true
              layout: horizontal
            state: 'on'
          - domain: light
            attributes:
              supported_features: < 44
            options:
              type: custom:mushroom-light-card
              show_brightness_control: true
              use_light_color: true
              show_color_temp_control: true
              show_color_control: false
              collapsible_controls: true
              layout: horizontal
            state: 'on'
          - entity_id: switch.*_light*
            state: 'on'
            options:
              type: custom:mushroom-light-card
              show_brightness_control: false
              use_light_color: true
              show_color_temp_control: false
              show_color_control: false
              collapsible_controls: true
              layout: horizontal
      show_empty: false
      card:
        square: false
        columns: 1
        type: grid
      card_param: cards
      sort:
        method: last_changed
        reverse: true
        numeric: false
  type: vertical-stack
```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2023.7.2
- Mushroom: 3.0.5
```

**Comment by fxxer** [comment]
I am not sure, if this is browser_mod bug or mushroom, I am linking this issue from browser_mod https://github.com/thomasloven/hass-browser_mod/issues/611

**Comment by S1M8N** [comment]
Patch with HA 2023.7.3 for me

**Comment by fxxer** [comment]
After 2023.7.3 it’s not working for me.

**Comment by sdoowo200leldls** [comment]
It's not working for me either on 2023.7.3. I re-posted the issue on the browser_mod side since it's not clear what is causing the issue. [https://github.com/thomasloven/hass-browser_mod/issues/618](url)

**Comment by sdoowo200leldls** [comment]
> After 2023.7.3 it’s not working for me.

Clearing cache in the app and browser fixed this for me both on android mobile and in Firefox.

**Comment by fxxer** [comment]
I cleared the cache on Chrome (Mac) also restart HA app on iOS and it's still not working

**Comment by mattclair** [comment]
After updating to  2023.07.1 everything is working in web browsers, but popups continue to be broken in the Andriod App. The odd thing I notice is that a number-card works while everything else is broken.

**Comment by robsonke** [comment]
I faced the same issue but it's solved with 2023.8.0 (and .1).

**Comment by fxxer** [comment]
Yes, everything is working in 2023.8.*

**Comment by mattclair** [comment]
I see this is closed but upgrading to 2023.8.1 did not resolve this for me. It works in web browsers but not in the companion app (Android).

**Comment by sdoowo200leldls** [comment]
> 

Did you clear the cache in the android app?

**Comment by mattclair** [comment]
How do you clear the cache for the android app? I've tried force closing the app but that doesn't do it. I would hope that I don't have to clear data, because that causes all kinds of headaches. I would have to re-register the device with HA and new entity names would be generated.
