### ISSUE TITLE
[Bug]: HVAC mode icons missing on Climate cards after 3.4.0 update

### ISSUE THREAD

**Issue by elarsson1** [piitaya/lovelace-mushroom#1360]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

After an update to Mushroom Cards v 3.4.0, Issue persists in 3.4.1. I am observing that icons for HVAC mode selection in the Mushroom climate card are no longer visible. See attached screenshot. 

This seems similar to #1359 but I am already running HA 2024.1.6, and it is not restricted to a particular device. Reproduced in Mozilla Firefox, Google Chrome, and IOS Companion App. Reverting Mushroom js files and refreshing the browser restores the icons. 

### Expected Behavior

HVAC Modes are shown with appropriate icons. 

### Steps To Reproduce

1. Update Mushroom card > 3.4.0 using HACS add-on
2. Refresh browser
3. Observe that HVAC mode icons have disappeared

### Context

Lovelace configuration for a climate card:

```
type: custom:mushroom-climate-card
entity: climate.living_room
show_temperature_control: true
hvac_modes:
  - heat
  - cool
  - 'off'
tap_action:
  action: more-info
```

### Environment

```markdown
- Browser: Firefox, Chrome, and iOS companion app
- HA Version: 2024.1.6
- Mushroom: 3.4.1
```

### Anything else?

<img width="454" alt="Screenshot 2024-02-03 at 12 23 00" src="https://github.com/piitaya/lovelace-mushroom/assets/6099938/f599b71f-b5b5-4734-a92b-d9186cbdfdf0">

**Comment by a1ex-ak** [comment]
I confirm the bug
![Снимок экрана от 2024-02-04 00-14-34](https://github.com/piitaya/lovelace-mushroom/assets/121604147/ca2879e9-b640-4245-9642-fb9a7654f1e0)

**Comment by clucluclu** [comment]
Also getting this

**Comment by BassBoi** [comment]
Same here: HA 2024.1.6 
Mushroom 3.4.1
![image](https://github.com/piitaya/lovelace-mushroom/assets/67754534/4a2ad783-6d7e-48d0-8e76-5c35e9b1026e)

**Comment by nicopret1** [comment]
Same here: Also on HA2024.1.6
Mushroom 3.4.1
![Screenshot 2024-02-04 at 14 36 34](https://github.com/piitaya/lovelace-mushroom/assets/130547447/2c1cfde6-f147-4163-9e7f-d8d2dcb54373)

**Comment by Gzzloveyyt** [comment]
![QQ截图20240205165350](https://github.com/piitaya/lovelace-mushroom/assets/25847375/52443f02-e49c-4d23-aaf1-b790ca035a91)

Same problem

**Comment by testsieger73** [comment]
![image](https://github.com/piitaya/lovelace-mushroom/assets/31756945/79ccb944-851a-4055-9cf8-7a9bb42aadee)

Same issue

**Comment by arwindersingh82** [comment]
Any updates on this bug?  Seems a lot of people are hitting this issue but no comments as to when this will be resolved?

**Comment by johnben345** [comment]
+1 also having this issue

**Comment by juscode** [comment]
Issue is the same after clearing cache and on latest version

**Comment by dm82m** [comment]
@piitaya issue is not fixed for cover cards:

![image](https://github.com/piitaya/lovelace-mushroom/assets/736311/55edb98b-d6c3-4b88-b459-b2f1baa323ee)

**Comment by dm82m** [comment]
And also some issues with entity card and humidifier card, see lower left side

**Comment by juscode** [comment]
Issue is still present for me too
![IMG_1638](https://github.com/piitaya/lovelace-mushroom/assets/36483778/bc791faf-b0bb-48d8-98fd-83e4d199d3aa)

**Comment by piitaya** [comment]
Hello 👋 It's certainly a cache issue. Try to clear it : https://github.com/piitaya/lovelace-mushroom?tab=readme-ov-file#i-dont-see-the-last-changes. Do you have the 4.3.2?

**Comment by dm82m** [comment]
Afaik google nest hub is not caching. Switched it of, powered it on but still the same result. Will test with a reboot of ha core.

**Comment by juscode** [comment]
Thank you resolved in 4.3.2

**Comment by dm82m** [comment]
@piitaya followed your advice, removed resource, uninstalled, reinstalled. Rebooted google nest hub. No change. Rebooted ha core and google nest hub. No change. Icons are still not shown. And yes: I am on version 4.3.2

**Comment by piitaya** [comment]
Is it only for climate card or also for all round icons?

**Comment by dm82m** [comment]
Totally confusing. All worked well with ha core 2024.1.5 and/or mushroom cards 3.4.0.

after upgrade all my mushroom cover cards are not showing an icon.

And the most confusing is that one mushroom entity card is showing an icon but the other card with the same configuration but other entity is not.

had the same problem with three custom:button-cards. Setting an icon manually solved the problem.

I would definitely say that caching is not an issue here. But I have no idea what the problem is.

**Comment by dm82m** [comment]
And this is the same here aswell: if I manually set the icons in my Lovelace config they are displayed. If I don’t set an icon it is sometimes displayed and sometimes not. Can’t figure out the reason. And can’t set icon for cover manually cause they are different depending on state.

**Comment by dm82m** [comment]
Tried downgrade to 3.3.0 of mushroom - same issue. Tried downgrade to ha core 2024.1.5 - same issue. Absolutely no idea when this problem started occuring. 😫

**Comment by dm82m** [comment]
Here is also a guy reporting about this issue in relation to button-card and a notice about a blog post that you wrote @piitaya see https://github.com/home-assistant/core/issues/109244
