### ISSUE TITLE
[Bug]: Can no longer see template editor with conditional chips as of 2025.5

### ISSUE THREAD

**Issue by mcanning** [piitaya/lovelace-mushroom#1703]
### Requirements

- [x] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [x] I did a search to see if there is a similar issue or if a pull request is open.
- [x] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

It seems there is not longer an option to edit the template as part of conditional chips. I had just upgraded to 2025.5 yesterday as I believe it was working the other day. See the screenshot which is missing the 'Card' tab.

![Image](https://github.com/user-attachments/assets/e18d876e-b768-4ee2-ace8-f81c485c46fa)

### Expected Behavior

Conditions and Card tabs

![Image](https://github.com/user-attachments/assets/6746de7f-bb41-4db4-a07b-a51c8089ef48)

### Steps To Reproduce

Create conditional  template chip on 2025.5 and attempt to modify the template using the UI

### Context

YAML state
```yaml
type: conditional
conditions:
  - condition: numeric_state
    entity: sensor.open_windows_count
    above: 0
chip:
  type: template
  content: '{{ states.sensor.open_windows_count.state }}'
  icon_color: |-
    {% if states("sensor.open_windows_count") > 0 %} primary {% elif
        states("sensor.open_windows_count") == "unavailable" %} black {% else %} grey
        {% endif %}
  icon: |-
    {% if states("sensor.open_windows_count") == "on" %} mdi:window-open {% elif
        states("sensor.open_windows_count") == "unavailable" %} mdi:alert-box-outline {% else %} mdi:window-closed
        {% endif %}
  entity: sensor.open_windows_count
  tap_action:
    action: more-info

```

### Environment

```markdown
- Browser: Google Chrome Version 134.0.6998.198 (Official Build) (64-bit)
- HA Version: 2025.5
- Mushroom: 4.4.0
```

### Anything else?

Please close if this is a dupe

**Comment by mikeschmick** [comment]
I'm having the same issue. Additional info:

If I edit yaml manually and switch back to visual it's still not there. Also, when I enter a color for the icon I have to add ' ' around the color like "'black'". The preview shows the change. When you save it reverts to no '' and the color does not work. 

Same behavior when adding new conditional chips as with editing old.

**Comment by iddiek** [comment]
Same

**Comment by dnestico** [comment]
Same, it's broken

**Comment by Olly77Wolly** [comment]
I have the same problem and would be extremely grateful if it could work again.

**Comment by Matze-aaa** [comment]
Same to me! What a pity...

**Comment by iddiek** [comment]
Still present ...

**Comment by Henry2808** [comment]
Just upgraded to 2025.7.2 hoping this error would magically go away with the restart, but still present now since May. Really somewhat of a nuisance as I have MANY conditional mushroom chips ;-)

**Comment by deadrubberboy** [comment]
Same here. It’s my most used dashboard element and they are all conditional.  I only use dashboard like “idiot lights” in a car.

**Comment by iddiek** [comment]
@piitaya please no one assigned in this bug from may... Isn't it relevant?

**Comment by piitaya** [comment]
I was busy last weeks so I didn't take a look. I will check that 👍

**Comment by Olly77Wolly** [comment]
Hi, is there perhaps a short update/info yet?

**Comment by piitaya** [comment]
Do you have other cards installed? I can not reproduce it when the latest version of Mushroom and latest version of HA. 
Also, do you have some errors in the browser console?

https://github.com/user-attachments/assets/76c0358b-8567-431d-a34c-a1720b29517f

**Comment by Henry2808** [comment]
@piitaya Thanks for looking into it. I am on 2025.7.2 and Mushroom 4.40 and unfortunately the error is persistent. The "Chip" tab is missing on all existing conditional chips (1st screenshot) and also missing when I create a new one (2nd screenshot) - just tried that even on a brand new and empty dashboard to make sure. The YAML-code is there, though and can also be edited. 
Concerning Browser errors I must admit I do not know where to look. Error ist the same in Safari 18.5 and Firefox 140.0.4 on macOS.

Thanks for your effort!

<img width="1049" height="632" alt="Image" src="https://github.com/user-attachments/assets/90f5db57-b3cf-4284-818b-0ec7bbc9fb1c" />

<img width="1049" height="569" alt="Image" src="https://github.com/user-attachments/assets/9f486a46-f87a-4e98-806b-7d3f3fe915f7" />

**Comment by Olly77Wolly** [comment]
Thank you for looking into the problem.

I can only say that I have tested these problems in all browsers. The same error exists in Edge and Chrome.

Thank you very much

**Comment by deadrubberboy** [comment]
I’m experiencing the same as Henry 2808. All updates current.

**Comment by Olly77Wolly** [comment]
The problem persists even with the new 2025.7.3 and Mushroom 4.40.

Just created a backup and removed everything to do with mushroom under HACS. Downloaded everything again after a reboot but unfortunately the problem persists.

<img width="498" height="636" alt="Image" src="https://github.com/user-attachments/assets/f0355529-0bb8-4c17-9580-b9a38033a291" />

**Comment by piitaya** [comment]
I found the issue, I will push a fix. Thank you for reporting.

The fix is available in the new [4.5.0 Mushroom release](https://github.com/piitaya/lovelace-mushroom/releases/tag/v4.5.0).

**Comment by Olly77Wolly** [comment]
I had just installed the update and rebooted. Unfortunately, the problem persists.

**Comment by Henry2808** [comment]
Version 4.5.0 fixed it for me (installed via HA frontend, browser cache emptied, no restart required).
Thanks again!

**Comment by deadrubberboy** [comment]
Confirmed! Fixed or me as well

**Comment by iddiek** [comment]
Thank you @piitaya

**Comment by Olly77Wolly** [comment]
Thank you very much. Now everything is running great again.
